### ISSUE TITLE
内存

### ISSUE THREAD

**Issue by ZinuoCai** [huangbiubiu/pytorch-datasets#2]
请问下载并能够使用youtube-vos数据集对服务器的内存要求多大？

**Comment by huangbiubiu** [comment]
因为我们服务器内存足够大，因此我们没有对内存方面进行测试。具体的内存消耗和模型配置有关。

**Comment by huangbiubiu** [comment]
关闭issue. 如果有进一步的问题请reopen.

**Comment by lx1374327576** [comment]
贵实验室服务器可以承受 具体我记不太清了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zinuo Cai"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月6日(星期五) 凌晨0:35
收件人:&nbsp;"huangbiubiu/pytorch-datasets"<pytorch-datasets@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[huangbiubiu/pytorch-datasets] 内存 (#2)




请问下载并能够使用youtube-vos数据集对服务器的内存要求多大？
